# Generated by Django 4.1.5 on 2023-01-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='sate',
            new_name='state',
        ),
    ]
